package ul.miage.patron.model.enumerations;

public enum GenreOeuvre {
    ROMANCE, POLICIER, HISTOIRE, SCIENCES, 
    GEOGRAPHIE, INFORMATIQUE, MATHEMATIQUES, 
    ART, CUISINE, SPORT, MUSIQUE, CINEMA, PHILOSOPHIE, 
    RELIGION, ECONOMIE, POLITIQUE, SCIENCE_FICTION, 
    HORREUR, FANTASTIQUE, AVENTURE, JEUNESSE, AUTRE
}
